from DbConnector import DbConnector
from tabulate import tabulate


class DbHandler:
    def __init__(self):
        self.connection = DbConnector()
        self.db_connection = self.connection.db_connection
        self.cursor = self.connection.cursor

    def create_table(self, tables: list):
        """Create tables and insert into DB
        Tables = [
            (
                "CREATE TABLE `employees` ("
                "  `emp_no` int(11) NOT NULL AUTO_INCREMENT,"
                "  `birth_date` date NOT NULL,"
                "  PRIMARY KEY (`emp_no`)"
                ")"
            ),
            (
                "CREATE TABLE `departments` ("
                "  `dept_no` char(4) NOT NULL,"
                "  `dept_name` varchar(40) NOT NULL,"
                "  PRIMARY KEY (`dept_no`)"
                ")"
            )
        ]

        Source: https://dev.mysql.com/doc/connector-python/en/connector-python-example-ddl.html
        """
        for table in tables:
            self.cursor.execute(table)
        self.db_connection.commit()

    def insert_data(self, table_name, columns, value):
        """Insert one row/item into database. Usefull when you need to autogenerated key

        Args:
            table_name (str): table to insert into
            columns (list): list of columns
            value (list): list of values

        Returns:
            _type_: _description_
        """
        # prepare data
        columns = ", ".join(columns)
        # Basically, convert the values and add single quote around strings
        value = prepare_values(value)

        # Prepare query
        query = "INSERT INTO %s(%s) VALUES(%s)"

        # Insert
        self.cursor.execute(query % (table_name, columns, value))
        self.db_connection.commit()
        return self.cursor.lastrowid

    def insert_batch_data(self, table_name, columns, values):
        """Insert multiple rows into table. Usefull when you do not need the autogenerated id,
        or you are providing it.

        Args:
            table_name (str): table to insert into
            columns (list): list of columns
            values (list[list]): a list containing list of values
        """
        # prepare data
        columns = ", ".join(columns)

        values = [prepare_values(i) for i in values]

        # Prepare query
        query = "INSERT INTO %s(%s)" % (table_name, columns)
        query = query + " VALUES(%s)"

        # Insert
        self.cursor.executemany(query, values)
        self.db_connection.commit()

    def drop_table(self, table_name):
        """Drop a table

        Args:
            table_name (str): name of table
        """
        print("Dropping table %s..." % table_name)
        query = "DROP TABLE %s"
        self.cursor.execute(query % table_name)

    def show_tables(self):
        """Print tables in database"""
        self.cursor.execute("SHOW TABLES")
        rows = self.cursor.fetchall()
        print(tabulate(rows, headers=self.cursor.column_names))


def prepare_values(value: list) -> str:
    return ", ".join(
        map(lambda x: "'" + str(x) + "'" if isinstance(x, str) else str(x), value)
    )
